dynamic_resources:
  lds_config:
    path: "/home/ubuntu/ml4sys-lb/envoy-config/lds.conf"
  cds_config:
    path: "/home/ubuntu/ml4sys-lb/envoy-config/cds.conf"
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
